apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipcode-lookup
  namespace: zipcode-app
  labels:
    app: zipcode-lookup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zipcode-lookup
  template:
    metadata:
      labels:
        app: zipcode-lookup
    spec:
      containers:
      - name: zipcode-lookup
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/zipcode-lookup:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"